### ISSUE TITLE
Enable Orthanc Explorer 2

### ISSUE THREAD

**Issue by zgypa** [open-ortho/ortho-tank#5]
The new explorer should allow the user to modify patient demographic data, which is an essential feature for a PACS to have. This should be enabled.

**Comment by exico91** [comment]
Enabled initial support for Orthanc Explorer 2, I enabled some options but we should check all the settings and enable/disable what we need.
We should also disable the old interface

**Comment by zgypa** [comment]
Ovena should be able to server following use cases:

- Acquire images from CBCT, Cameras and other modalities in DIMSE
- Make corrections to the following DICOM tags:
    - Patient Name
    - DOB
    - Patient ID
- Check that PACS contains a specific Study
- Visualize a specific Study
-  Send Study/Series to another workstation
- Upload images
- Delete Studies
- Change settings
    - Allowed workstations to send studies to
    - Admin users management (new user, modify, change password)
    - Workstation users management to give remove WADO/DIMSE access to workstations
- Web Admin interface protected with username/password
- API to make mass corrections

**Comment by zgypa** [comment]
Merged into develop.
